apiVersion: v1
kind: Config
preferences: {}
clusters:
- cluster:
  name: development
- cluster:
  name: scratch
contexts:
- name: development@developer-fe
  context:
    cluster: development
    user: developer-fe
- context:
  name: dev-storage
- context:
  name: exp-scratch
users:
- name: developer-fe
- name: developer-be
- name: experimenter