apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: app
  name: app
spec:
  volumes:
    - name: app-volume
      persistentVolumeClaim:
        claimName: pvc
  containers:
  - image: nginx
    name: nginx
    resources: {}
    volumeMounts:
      - name: app-volume
        mountPath: /var/app/config
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
