apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: alpine-pod
  name: alpine-pod
spec:
  volumes:
    - name: my-volume
      emptyDir: {}
  containers:
  - image: alpine:3.12.0
    name: alpine-a
    args:
      - /bin/sh
      - -c
      - while true; do sleep 60; done;
    volumeMounts:
    - name: my-volume
      mountPath: /etc/a
  - image: alpine:3.12.0
    name: alpine-b
    args:
      - /bin/sh
      - -c
      - while true; do sleep 60; done;
    volumeMounts:
    - name: my-volume
      mountPath: /etc/b
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}